fos_rest:
    view:
        view_response_listener:  true
    zone:
    - { path: '^/api/.*' }
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
            - { path: ^/, prefer_extension: true, fallback_format: html, priorities: [ html, '*/*' ] }
    exception:
        exception_controller: 'fos_rest.exception.controller:showAction'
        codes:
            Doctrine\ORM\EntityNotFoundException: 404
        messages:
            Doctrine\ORM\EntityNotFoundException: true


