<?php

namespace App\Entity\Order;

use Sylius\Component\Inventory\Model\StockableInterface;
use Sylius\Component\Order\Model\OrderItemInterface;
use Sylius\Component\Order\Model\OrderItemUnit as SyliusOrderItemUnit;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="sylius_order_item_unit")
 */
class OrderItemUnit extends SyliusOrderItemUnit implements OrderItemUnitInterface
{
    /**
     * @inheritDoc
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue
     */
    protected $id;

    /**
     * @inheritDoc
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Order\OrderItem", inversedBy="units")
     */
    protected $orderItem;

    /**
     * @inheritDoc
     *
     * @ORM\OneToMany(targetEntity="Adjustment", mappedBy="orderItemUnit")
     */
    protected $adjustments;

    /**
     * @inheritDoc
     *
     * @ORM\Column(type="integer", name="adjustment_total")
     */
    protected $adjustmentsTotal = 0;

    public function getOrderItem(): OrderItemInterface
    {
        return parent::getOrderItem(); // TODO: Change the autogenerated stub
    }

    public function getStockable(): ?StockableInterface
    {
        return $this->orderItem->getVariant();
    }
}
